### ISSUE TITLE
Key "dist" missing

### ISSUE THREAD

**Issue by gmauro** [ht-diva/gwaspipe#4]
https://github.com/ht-diva/gwaspipe/blob/f92de7d3ff78e614796bcd5644c9e4416e244386/src/gwaspipe.py#L125

Ehi @MichCM , gwaslab doesn't recognize the key "dist" as valid for the plot_mmq function.
Is this a typo or what do you mean?

**Comment by gmauro** [comment]
Is it an argument for gwaslab or not?

**Comment by MichCM** [comment]
It is not a parameter from gwaslab, it is needed to compute the 'cut' though. This is why I was including it as a "param" and not a "gl_param". But maybe I messed up somewhere when passing the dictionaries

**Comment by gmauro** [comment]
The key missing issue is fixed but now I have this:

Tue Feb  6 15:12:15 2024 Start to create manhattan plot with 1391097 variants:
Tue Feb  6 15:12:17 2024  -Found 1 significant variants with a sliding window size of 500 kb...
Tue Feb  6 15:12:17 2024 Finished creating Manhattan plot successfully!
Tue Feb  6 15:12:17 2024  -Skip annotating
Tue Feb  6 15:12:17 2024 Start to create QQ plot with 1391097 variants:
Traceback (most recent call last):
  File "/Users/gianmauro.cuccuru/version/gmauro/gwaspipe/src/gwaspipe.py", line 137, in <module>
    main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gianmauro.cuccuru/version/gmauro/gwaspipe/src/gwaspipe.py", line 126, in main
    sm.mysumstats.plot_mqq(cut = cut, save = output_path, **gl_params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/gwaslab/g_Sumstats.py", line 517, in plot_mqq
    plot = mqqplot(self.data,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/gwaslab/viz_plot_mqqplot.py", line 880, in mqqplot
    ax2 =_plot_qq(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/gwaslab/viz_plot_qqplot.py", line 84, in _plot_qq
    databin = sumstats.loc[(sumstats["MAF"]>lower) &( sumstats["MAF"]<=upper),["MAF","scaled_P"]]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/pandas/core/arraylike.py", line 56, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/pandas/core/series.py", line 5623, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 280, in comparison_op
    return invalid_comparison(lvalues, rvalues, op)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gwaspipe/lib/python3.10/site-packages/pandas/core/ops/invalid.py", line 34, in invalid_comparison
    raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
TypeError: Invalid comparison between dtype=float32 and str

**Comment by gmauro** [comment]
I moved one step forward and in 'mode=m' it works, so it seems to be the qq part that is showing the problem.

**Comment by gmauro** [comment]
In the end, it was the way I defined the  maf_bins argument in the yaml format
